### ISSUE TITLE
drawing a vertical line the full height of the display overruns the stack buffer

### ISSUE THREAD

**Issue by bradanlane** [fdufnews/SMART-Response-XE-Low_level#2]
It appears I encountered a bug.

A vertical line uses a stack buffer to hold the color byte. The buffer is 128 bytes but there are 136 rows on the LCD.

test case:  `SRXEVerticalLine(30, 0, 136, 3);`

```
void SRXEVerticalLine(int x, int y, int height, byte color) {
  byte bTemp[128];

  SRXESetPosition(x * 3, y, 1, height );
  memset(bTemp, bColorToByte[color], height);
  SRXEWriteDataBlock(bTemp, height);
}
```

I presume the bTemp stack buffer needs to be 136 bytes?

**Comment by fdufnews** [comment]
Thanks for the report
I have made the correction, an updated hello_world to draw vertical lines the height of the screen.
